# logging: true
env_name: Gspuzzle
log_path: "logs"
runner:
  max_steps: 400
env:
  state_path: "C:/Users/HSGamer/Downloads/GSPuzzle-Build/PlayerLog.txt"
  result_path: "C:/Users/HSGamer/Downloads/GSPuzzle-Build/PlayData"
  task: Complete the 2 puzzles
  final_level: Level_2
  sleep_time: 3
  input_modality: "text_image"  # "text", "text_image"
  window_capture_mode: "bitblt"  # "bitblt", "mss", "dxcam"
  image_max_bytes: 5242880
  io_env:
    env_name: "Gspuzzle"
    win_name_pattern: "^GSPuzzle$"

# agent configuration
agent:
  llm_name: gpt-4o
  api_key: "token-abc123"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 0.3
  repetition_penalty: 1.0
  agent_type: zeroshot_agent
  prompt_path: mcp_agent_servers.gspuzzle.prompts.text_image.zeroshot_agent

# mcp configuration
game_server: "./src/mcp_game_servers/gspuzzle/server.py"
agent_server: "./src/mcp_agent_servers/gspuzzle/server.py"
